In [1]:
from taxcalc import *
import pandas as pd
import numpy as np

In [2]:
recs = Records()
pol = Policy()
calc = Calculator(records=recs, policy=pol)
calc.advance_to_year(2014)
calc.calc_all()

taxcalc/behavior.py:190: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  val = values[year]


You loaded data for 2009.
Instantiation of the calculator automatically extrapolated your data to 2013.


In [3]:
was = np.corrcoef([calc.records.e00200, calc.records.e00300])

In [4]:
was

array([[ 1.        ,  0.08944197],
       [ 0.08944197,  1.        ]])

In [5]:
divs = np.corrcoef([calc.records.e00600, calc.records.e00300])

In [6]:
divs

array([[ 1.       ,  0.2058408],
       [ 0.2058408,  1.       ]])

In [7]:
qdivs = np.corrcoef([calc.records.e00650, calc.records.e00300])

In [8]:
qdivs

array([[ 1.        ,  0.15448049],
       [ 0.15448049,  1.        ]])

In [9]:
biz = np.corrcoef([calc.records.e00900, calc.records.e00300])

In [10]:
biz

array([[ 1.        ,  0.00168549],
       [ 0.00168549,  1.        ]])

In [11]:
cgns = np.corrcoef([calc.records.c01000, calc.records.e00300])

In [12]:
cgns

array([[ 1.       ,  0.1697013],
       [ 0.1697013,  1.       ]])

In [13]:
rwas = calc.records.e00200 / calc.records.e00300